<?php

namespace strtob\yii2Ollama\Adapter;

/**
 * Interface for vector database clients.
 *
 * Any vector database you want to integrate with `OllamaComponent`
 * must implement this interface. The component will use it to:
 *   1. Retrieve top-K relevant context for prompt injection.
 *   2. Store embeddings (vectors) generated by the model.
 *
 * Example Qdrant adapter implementation:
 *
 * ```php
 * use strtob\yii2Ollama\Adapter\VectorDbInterface;
 *
 * class QdrantClientAdapter implements VectorDbInterface
 * {
 *     protected $qdrantClient;
 *
 *     public function __construct($qdrantClient)
 *     {
 *         $this->qdrantClient = $qdrantClient;
 *     }
 *
 *     public function search(string $query, int $topK = 5): array
 *     {
 *         $results = $this->qdrantClient->search($query, $topK);
 *         return array_map(fn($item) => $item['text'], $results);
 *     }
 *
 *     public function upsert(array $vectorData): void
 *     {
 *         // $vectorData = [
 *         //    'id' => string,
 *         //    'vector' => array of floats,
 *         //    'payload' => ['text' => ..., 'source' => ...]
 *         // ]
 *         $this->qdrantClient->upsert($vectorData);
 *     }
 * }
 * ```
 *
 * Usage in `OllamaComponent` config:
 *
 * ```php
 * $qdrantAdapter = new QdrantClientAdapter($qdrantClient);
 *
 * 'components' => [
 *     'ollama' => [
 *         'class' => 'strtob\yii2Ollama\OllamaComponent',
 *         'apiUrl' => 'http://localhost:11434/v1/generate',
 *         'apiKey' => 'MY_SECRET_TOKEN',
 *         'vectorDb' => $qdrantAdapter,
 *         'vectorDbTopK' => 5,
 *     ],
 * ];
 * ```
 *
 * @package strtob\yii2Ollama
 */
interface VectorDbInterface
{
    /**
     * Search the vector DB for relevant context.
     *
     * @param string $query Query text or embedding (depending on implementation)
     * @param int $topK Number of top results to return
     * @return string[] Array of strings representing context
     */
    public function search(string $query, int $topK = 5): array;

    /**
     * Insert or update a vector with payload into the vector DB.
     *
     * @param array $vectorData Must include:
     *   - 'id' => unique identifier
     *   - 'vector' => array of floats (embedding)
     *   - 'payload' => associative array with metadata (e.g., 'text', 'source')
     */
    public function upsert(array $vectorData): void;

        /**
     * Search by a precomputed embedding vector.
     *
     * @param array $embedding Numeric vector
     * @param int $topK Number of results
     * @return string[] Array of text payloads
     */
    public function searchByVector(array $embedding, int $topK = 5): array;
}

